name: themovedb
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.11.1
  flutter_secure_storage: ^5.0.2
  cupertino_icons: ^1.0.2
  spider: ^2.2.2
  json_annotation: ^4.6.0
  flutter_localizations:
     sdk: flutter
  intl: ^0.17.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  build_runner: ^2.2.0

  
  flutter_lints: ^1.0.0
  

flutter:

  
  uses-material-design: true

 
  assets:
    - images/

  